# -*- coding: utf-8 -*-
"""analysis(iqf)ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWyyDiu7eGbNrx7CrnVrL8rPcZ_hY8ZA
"""

"""
Mutual Fund Performance Persistence Analysis
=============================================
Inputs:
  - mf_filtered_wide.csv          : monthly returns, rows=months, cols=fund names
  - nifty50_monthly.csv           : optional, columns [Month, Nifty50_Return]
  - india_vix_monthly.csv         : optional, columns [Month, VIX]
  - factors_monthly.csv           : optional, columns [Month, MKT, SMB, HML, MOM]

Outputs:
  - results/quintile_returns.csv          : avg return per quintile per period
  - results/transition_matrix_raw.csv     : full-sample transition matrix (raw)
  - results/transition_matrix_bm.csv      : full-sample transition matrix (BM-adjusted)
  - results/transition_matrix_alpha.csv   : full-sample transition matrix (alpha)
  - results/transition_matrix_<regime>.csv: per market regime transition matrices
  - results/regression_results.csv        : persistence regression coefficients
  - results/summary_report.txt            : human-readable summary

Requirements:
    pip install pandas numpy scipy statsmodels

Run:
    python mf_persistence_analysis.py
"""

import pandas as pd
import numpy as np
import os
import warnings
from datetime import datetime
warnings.filterwarnings("ignore")

# ── Try importing statsmodels (needed for regression) ──
try:
    import statsmodels.formula.api as smf
    HAS_STATSMODELS = True
except ImportError:
    HAS_STATSMODELS = False
    print("Warning: statsmodels not found. Regression section will be skipped.")
    print("Install with: pip install statsmodels")

# ─────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────
INPUT_WIDE       = "mf_filtered_wide.csv"
INPUT_NIFTY      = "nifty50_monthly.csv"    # optional
INPUT_VIX        = "india_vix_monthly.csv"  # optional
INPUT_FACTORS    = "factors_monthly.csv"    # optional

RESULTS_DIR      = "results"
RANKING_WINDOW   = 12   # months used to rank funds
HOLDING_WINDOW   = 12   # months of forward performance to evaluate
N_QUINTILES      = 5    # 5 = quintiles, can set to 4 for quartiles

# VIX threshold to define high-volatility regime
VIX_HIGH_THRESH  = 20.0

os.makedirs(RESULTS_DIR, exist_ok=True)


# ─────────────────────────────────────────
# STEP 1: Load data
# ─────────────────────────────────────────
def load_data():
    print("=" * 60)
    print("Loading data ...")

    # Wide returns — index = Month (YYYY-MM string), cols = fund names
    df_wide = pd.read_csv(INPUT_WIDE, index_col=0)
    df_wide.index = pd.PeriodIndex(df_wide.index, freq="M")
    df_wide = df_wide.sort_index()
    print(f"  Returns : {df_wide.shape[0]} months × {df_wide.shape[1]} funds")
    print(f"  Window  : {df_wide.index[0]} → {df_wide.index[-1]}")

    # Nifty 50 benchmark (optional)
    nifty = None
    if os.path.exists(INPUT_NIFTY):
        nifty = pd.read_csv(INPUT_NIFTY, index_col=0)
        nifty.index = pd.PeriodIndex(nifty.index, freq="M")
        nifty = nifty.sort_index().squeeze()
        print(f"  Nifty50 : loaded ({len(nifty)} months)")
    else:
        print(f"  Nifty50 : NOT FOUND — benchmark-adjusted returns will be skipped")

    # India VIX (optional)
    vix = None
    if os.path.exists(INPUT_VIX):
        vix = pd.read_csv(INPUT_VIX, index_col=0)
        vix.index = pd.PeriodIndex(vix.index, freq="M")
        vix = vix.sort_index().squeeze()
        print(f"  VIX     : loaded ({len(vix)} months)")
    else:
        print(f"  VIX     : NOT FOUND — volatility regime will use Nifty std dev as proxy")

    # Factors (optional)
    factors = None
    if os.path.exists(INPUT_FACTORS):
        factors = pd.read_csv(INPUT_FACTORS, index_col=0)
        factors.index = pd.PeriodIndex(factors.index, freq="M")
        factors = factors.sort_index()
        print(f"  Factors : loaded ({len(factors)} months, cols: {list(factors.columns)})")
    else:
        print(f"  Factors : NOT FOUND — factor-adjusted alpha will be skipped")

    return df_wide, nifty, vix, factors


# ─────────────────────────────────────────
# STEP 2: Define market regimes
# ─────────────────────────────────────────
def define_regimes(df_wide, nifty, vix):
    """
    Classify each month into: Bull / Bear / High Volatility
    Logic:
      - Use Nifty 12M rolling return to define Bull/Bear
        Bull  : trailing 12M Nifty return > 0
        Bear  : trailing 12M Nifty return < 0
      - High Volatility: VIX > VIX_HIGH_THRESH (or cross-sectional std dev proxy)
      - A month can be tagged as High Volatility AND Bull/Bear simultaneously
    """
    months = df_wide.index

    if nifty is not None:
        nifty_aligned = nifty.reindex(months)
        # Rolling 12M cumulative return for Nifty
        nifty_cum = (1 + nifty_aligned / 100).rolling(12).apply(np.prod, raw=True) - 1
        bull_mask = nifty_cum > 0
        bear_mask = nifty_cum <= 0
    else:
        # Fallback: use median fund return as market proxy
        mkt_proxy = df_wide.median(axis=1)
        mkt_cum   = (1 + mkt_proxy / 100).rolling(12).apply(np.prod, raw=True) - 1
        bull_mask = mkt_cum > 0
        bear_mask = mkt_cum <= 0

    if vix is not None:
        vix_aligned  = vix.reindex(months)
        highvol_mask = vix_aligned > VIX_HIGH_THRESH
    else:
        # Fallback: cross-sectional std dev of fund returns as volatility proxy
        cs_std       = df_wide.std(axis=1)
        highvol_mask = cs_std > cs_std.quantile(0.75)

    regimes = pd.DataFrame({
        "Bull":        bull_mask,
        "Bear":        bear_mask,
        "HighVol":     highvol_mask,
    }, index=months)

    # Primary regime label (mutually exclusive, HighVol takes precedence)
    def label(row):
        if pd.isna(row["Bull"]):
            return "Unknown"
        if row["HighVol"]:
            return "HighVol"
        if row["Bull"]:
            return "Bull"
        return "Bear"

    regimes["Regime"] = regimes.apply(label, axis=1)

    print("\nMarket regime distribution:")
    print(regimes["Regime"].value_counts().to_string())
    return regimes


# ─────────────────────────────────────────
# STEP 3: Compute benchmark-adjusted returns
# ─────────────────────────────────────────
def compute_bm_adjusted(df_wide, nifty):
    if nifty is None:
        return None
    nifty_aligned = nifty.reindex(df_wide.index)
    df_bm = df_wide.subtract(nifty_aligned, axis=0)
    return df_bm


# ─────────────────────────────────────────
# STEP 4: Compute factor-adjusted alpha (rolling OLS)
# ─────────────────────────────────────────
def compute_factor_alpha(df_wide, factors):
    """
    For each fund, run rolling 24-month OLS of fund return on factors.
    Alpha = intercept (annualised).
    Returns DataFrame of same shape as df_wide with monthly alpha estimates.
    """
    if factors is None or not HAS_STATSMODELS:
        return None

    import statsmodels.api as sm

    ROLL_WINDOW = 24
    alpha_df = pd.DataFrame(index=df_wide.index, columns=df_wide.columns, dtype=float)

    factor_cols = [c for c in ["MKT", "SMB", "HML", "MOM"] if c in factors.columns]
    if not factor_cols:
        print("  Factor columns not found — check factors CSV has MKT/SMB/HML/MOM")
        return None

    X_full = sm.add_constant(factors[factor_cols])

    for fund in df_wide.columns:
        y = df_wide[fund]
        for t in range(ROLL_WINDOW, len(df_wide.index)):
            period = df_wide.index[t - ROLL_WINDOW: t]
            y_roll = y.reindex(period).dropna()
            X_roll = X_full.reindex(period).dropna()
            idx    = y_roll.index.intersection(X_roll.index)
            if len(idx) < 18:
                continue
            try:
                res = sm.OLS(y_roll.loc[idx], X_roll.loc[idx]).fit()
                alpha_df.loc[df_wide.index[t], fund] = res.params["const"] * 12  # annualise
            except Exception:
                continue

    print(f"  Factor alpha computed ({alpha_df.notna().sum().sum():,} estimates)")
    return alpha_df


# ─────────────────────────────────────────
# STEP 5: Core persistence engine
# ─────────────────────────────────────────
def compute_rolling_quintiles(returns_df, label="raw"):
    """
    For each ranking period t:
      - Rank funds on trailing RANKING_WINDOW cumulative return
      - Assign quintile Q1 (worst) to Q5 (best)
      - Track their average return over next HOLDING_WINDOW months
    Returns:
      - quintile_series : DataFrame [period, fund] → quintile label
      - forward_returns : DataFrame [period, fund] → forward avg monthly return
    """
    months    = returns_df.index
    all_dates = []
    all_funds = []
    all_quint = []
    all_fwd   = []
    all_rank_ret = []

    step = 6  # roll forward every 6 months (non-overlapping would be 12)

    for i in range(RANKING_WINDOW, len(months) - HOLDING_WINDOW, step):
        rank_period = months[i - RANKING_WINDOW: i]
        hold_period = months[i: i + HOLDING_WINDOW]

        # Trailing cumulative return for ranking
        rank_rets = returns_df.loc[rank_period].dropna(axis=1, how="any")
        if rank_rets.shape[1] < N_QUINTILES * 2:
            continue
        cum_rank = (1 + rank_rets / 100).prod() - 1

        # Quintile assignment
        try:
            quintiles = pd.qcut(cum_rank, N_QUINTILES,
                                labels=[f"Q{j}" for j in range(1, N_QUINTILES + 1)])
        except ValueError:
            continue

        # Forward returns
        fwd_rets = returns_df.loc[hold_period, rank_rets.columns].mean()

        for fund in rank_rets.columns:
            all_dates.append(str(months[i]))
            all_funds.append(fund)
            all_quint.append(str(quintiles[fund]))
            all_fwd.append(fwd_rets[fund])
            all_rank_ret.append(float(cum_rank[fund]) * 100)

    df_out = pd.DataFrame({
        "RankingDate":    all_dates,
        "Fund":           all_funds,
        "Quintile":       all_quint,
        "RankReturn_pct": all_rank_ret,
        "FwdReturn_monthly": all_fwd,
    })

    return df_out


# ─────────────────────────────────────────
# STEP 6: Transition matrix
# ─────────────────────────────────────────
def build_transition_matrix(quint_df, label="raw"):
    """
    Builds a Q×Q transition matrix showing what fraction of funds
    in quintile Q_t end up in quintile Q_{t+1}.
    """
    quint_labels = [f"Q{j}" for j in range(1, N_QUINTILES + 1)]

    # Pivot: rows = RankingDate, cols = Fund, vals = Quintile
    pivot = quint_df.pivot(index="RankingDate", columns="Fund", values="Quintile")
    dates = pivot.index.tolist()

    trans = pd.DataFrame(0.0, index=quint_labels, columns=quint_labels)
    counts = pd.DataFrame(0, index=quint_labels, columns=quint_labels)

    for i in range(len(dates) - 1):
        curr = pivot.loc[dates[i]].dropna()
        nxt  = pivot.loc[dates[i + 1]].dropna()
        common = curr.index.intersection(nxt.index)
        for fund in common:
            q_curr = curr[fund]
            q_next = nxt[fund]
            if q_curr in quint_labels and q_next in quint_labels:
                counts.loc[q_curr, q_next] += 1

    # Row-normalise to get probabilities
    row_sums = counts.sum(axis=1)
    for q in quint_labels:
        if row_sums[q] > 0:
            trans.loc[q] = counts.loc[q] / row_sums[q] * 100

    trans.index.name   = f"From \\ To ({label})"
    trans = trans.round(1)
    return trans, counts


# ─────────────────────────────────────────
# STEP 7: Quintile average returns table
# ─────────────────────────────────────────
def quintile_avg_returns(quint_df):
    if quint_df.empty or quint_df["Quintile"].nunique() < 2:
        return pd.DataFrame(), 0.0

    summary = (
        quint_df.groupby("Quintile")["FwdReturn_monthly"]
        .agg(["mean", "median", "std", "count"])
        .rename(columns={
            "mean":   "Avg Fwd Monthly Return (%)",
            "median": "Median Fwd Monthly Return (%)",
            "std":    "Std Dev (%)",
            "count":  "Observations"
        })
        .round(4)
    )
    # Spread: Q5 - Q1 (guard if either quintile missing)
    if "Q5" not in summary.index or "Q1" not in summary.index:
        return summary, 0.0
    spread = summary.loc["Q5", "Avg Fwd Monthly Return (%)"] - \
             summary.loc["Q1", "Avg Fwd Monthly Return (%)"]
    return summary, spread


# ─────────────────────────────────────────
# STEP 8: Persistence regression
# ─────────────────────────────────────────
def run_persistence_regression(quint_df, label="raw"):
    """
    FwdReturn = α + β × RankReturn + ε
    β > 0 and significant → persistence
    """
    if not HAS_STATSMODELS:
        return None

    import statsmodels.formula.api as smf

    df = quint_df.dropna(subset=["RankReturn_pct", "FwdReturn_monthly"])
    if len(df) < 30:
        return None

    model = smf.ols("FwdReturn_monthly ~ RankReturn_pct", data=df).fit()
    result = {
        "Measure":    label,
        "Beta":       round(model.params["RankReturn_pct"], 4),
        "Alpha":      round(model.params["Intercept"], 4),
        "R_squared":  round(model.rsquared, 4),
        "p_value":    round(model.pvalues["RankReturn_pct"], 4),
        "N":          len(df),
        "Significant": "Yes" if model.pvalues["RankReturn_pct"] < 0.05 else "No"
    }
    return result


# ─────────────────────────────────────────
# STEP 9: Per-regime analysis
# ─────────────────────────────────────────
def regime_analysis(quint_df, regimes, label="raw"):
    """
    Filter quint_df to months belonging to each regime,
    then build transition matrix and avg returns per regime.
    """
    results = {}
    for regime in ["Bull", "Bear", "HighVol"]:
        regime_months = regimes[regimes["Regime"] == regime].index
        regime_months_str = [str(m) for m in regime_months]

        sub = quint_df[quint_df["RankingDate"].isin(regime_months_str)]
        if len(sub) < 20:
            print(f"  [{label}] {regime}: too few observations ({len(sub)}), skipping")
            continue

        tm, _ = build_transition_matrix(sub, label=f"{label}_{regime}")
        avg, spread = quintile_avg_returns(sub)
        results[regime] = {"transition": tm, "avg_returns": avg, "spread": spread}
        print(f"  [{label}] {regime}: {len(sub)} fund-periods, Q5-Q1 spread = {spread:.4f}%/month")

    return results


# ─────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────
def main():
    print("=" * 60)
    print("MF Persistence Analysis Pipeline")
    print(f"Ranking window : {RANKING_WINDOW} months")
    print(f"Holding window : {HOLDING_WINDOW} months")
    print(f"Quintiles      : {N_QUINTILES}")
    print("=" * 60)

    # Ensure results directory exists
    os.makedirs(RESULTS_DIR, exist_ok=True)

    # Load
    df_wide, nifty, vix, factors = load_data()

    # Regimes
    print("\nDefining market regimes ...")
    regimes = define_regimes(df_wide, nifty, vix)
    regimes.to_csv(f"{RESULTS_DIR}/market_regimes.csv")

    # Return measures
    measures = {"raw": df_wide}

    df_bm = compute_bm_adjusted(df_wide, nifty)
    if df_bm is not None:
        measures["benchmark_adjusted"] = df_bm
        print("  Benchmark-adjusted returns: ready")
    else:
        print("  Benchmark-adjusted returns: SKIPPED (no Nifty data)")

    print("  Computing factor alphas (this may take a few minutes) ...")
    df_alpha = compute_factor_alpha(df_wide, factors)
    if df_alpha is not None:
        measures["factor_alpha"] = df_alpha
        print("  Factor-adjusted alpha: ready")
    else:
        print("  Factor-adjusted alpha: SKIPPED (no factor data or statsmodels)")

    # Run analysis for each measure
    all_transitions = {}
    all_avg_returns  = {}
    regression_rows  = []

    for measure_label, ret_df in measures.items():
        print(f"\n{'─'*50}")
        print(f"Analysing: {measure_label.upper()}")
        print(f"{'─'*50}")

        # Rolling quintiles
        print("  Computing rolling quintiles ...")
        quint_df = compute_rolling_quintiles(ret_df, label=measure_label)
        print(f"  Fund-period observations: {len(quint_df):,}")

        # Full-sample transition matrix
        tm, counts = build_transition_matrix(quint_df, label=measure_label)
        all_transitions[measure_label] = tm
        tm.to_csv(f"{RESULTS_DIR}/transition_matrix_{measure_label}.csv")
        print(f"\n  Transition matrix ({measure_label}):")
        print(tm.to_string())

        # Quintile average returns
        avg_rets, spread = quintile_avg_returns(quint_df)
        all_avg_returns[measure_label] = avg_rets
        avg_rets.to_csv(f"{RESULTS_DIR}/quintile_returns_{measure_label}.csv")
        print(f"\n  Quintile avg forward returns ({measure_label}):")
        print(avg_rets.to_string())
        print(f"  Q5−Q1 spread: {spread:.4f}% per month")

        # Regression
        reg = run_persistence_regression(quint_df, label=measure_label)
        if reg:
            regression_rows.append(reg)

        # Per-regime
        print(f"\n  Regime-level analysis ({measure_label}):")
        regime_res = regime_analysis(quint_df, regimes, label=measure_label)
        for regime, res in regime_res.items():
            res["transition"].to_csv(
                f"{RESULTS_DIR}/transition_matrix_{measure_label}_{regime}.csv"
            )
            if not res["avg_returns"].empty:
                res["avg_returns"].to_csv(
                    f"{RESULTS_DIR}/quintile_returns_{measure_label}_{regime}.csv"
                )

    # Regression summary
    if regression_rows:
        reg_df = pd.DataFrame(regression_rows)
        reg_df.to_csv(f"{RESULTS_DIR}/regression_results.csv", index=False)
        print(f"\n{'─'*50}")
        print("REGRESSION RESULTS (FwdReturn ~ PastReturn)")
        print(f"{'─'*50}")
        print(reg_df.to_string(index=False))

    # ── Text summary report ──
    report_lines = [
        "MUTUAL FUND PERSISTENCE ANALYSIS — SUMMARY REPORT",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"Ranking window: {RANKING_WINDOW}M | Holding window: {HOLDING_WINDOW}M",
        "=" * 60,
        "",
        "RETURN MEASURES ANALYSED:",
    ]
    for m in measures:
        report_lines.append(f"  - {m}")

    report_lines += ["", "FULL-SAMPLE TRANSITION MATRICES:", ""]
    for m, tm in all_transitions.items():
        report_lines.append(f"  [{m}]")
        report_lines.append(tm.to_string())
        report_lines.append("")

    report_lines += ["Q5−Q1 SPREAD SUMMARY (avg monthly fwd return):"]
    for m, avg in all_avg_returns.items():
        if avg.empty or "Q5" not in avg.index or "Q1" not in avg.index:
            report_lines.append(f"  {m:30s}: N/A (insufficient data)")
            continue
        q5 = avg.loc["Q5", "Avg Fwd Monthly Return (%)"]
        q1 = avg.loc["Q1", "Avg Fwd Monthly Return (%)"]
        report_lines.append(f"  {m:30s}: {q5-q1:+.4f}% / month")

    if regression_rows:
        report_lines += ["", "REGRESSION — PERSISTENCE BETA (β):"]
        for r in regression_rows:
            report_lines.append(
                f"  {r['Measure']:30s}: β={r['Beta']:+.4f}, p={r['p_value']:.4f}, "
                f"R²={r['R_squared']:.4f}, Significant={r['Significant']}"
            )

    report_path = f"{RESULTS_DIR}/summary_report.txt"
    with open(report_path, "w") as f:
        f.write("\n".join(report_lines))

    print(f"\n{'='*60}")
    print("ALL DONE")
    print(f"{'='*60}")
    print(f"Output folder: {RESULTS_DIR}/")
    for fname in sorted(os.listdir(RESULTS_DIR)):
        print(f"  {fname}")


if __name__ == "__main__":
    main()